---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
  labels:
    app: e-commerce
spec:
  selector:
    matchLabels:
      app: e-commerce
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  minReadySeconds: 60
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app: harrison
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: capstone
        image: {../ repository image path  /..}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          successThreshold: 1
          periodSeconds: 30
          failureThreshold: 3
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: "service-e-commerce"
spec:
  selector:
    app: capstone
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80